// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Doctor          string
	FavoriteDoctors string
	Illness         string
	User            string
	UserIllness     string
	Visit           string
}{
	Doctor:          "doctor",
	FavoriteDoctors: "favorite_doctors",
	Illness:         "illness",
	User:            "user",
	UserIllness:     "user_illness",
	Visit:           "visit",
}
